### ISSUE TITLE
Broken in Archlinux

### ISSUE THREAD

**Issue by ak5** [KenjiTakahashi/pacmixer#12]
Hi, I saw that you also submitted this to AUR, so I thought I'd post this here.

I am getting this error when attempting to start pacmixer.

pacmixer: error while loading shared libraries: libpanelw.so.5: cannot open shared object file: No such file or direct

Thanks for the tool!

**Comment by KenjiTakahashi** [comment]
Are you using the latest AUR package (0.6.2-*2*)? I have recently pushed a updated AUR package that ought to fix this. Basically, you're still linked to ncurses 5.9, while Arch has been updated to 6.0, which required a rebuild.

**Comment by KenjiTakahashi** [comment]
Guess I can close this one? Feel free to reopen if there are still any problems.
