### ISSUE TITLE
pacmixer depending on specific version of libgnustep-base

### ISSUE THREAD

**Issue by tsaodown** [KenjiTakahashi/pacmixer#22]
OS: Arch Linux 5.12.5

Was getting the following error when trying to run `pacmixer`:

```
pacmixer: error while loading shared libraries: libgnustep-base.so.1.27: cannot open shared object file: No such file or directory
```

`libgnustep-base` was updated to 1.28.0 in Arch core package repository, causing my system to lose `libgnustep-base.so.1.27`.  I patched this locally by symlinking `/usr/lib/libgnustep-base.so.1.27` to `/usr/lib/libgnustep-base.so`.

I would submit a PR for this myself, but it's been a while since I've worked with languages that require linking. Seems like if we could get `pacmixer` to link to the symlinked (versionless) `libgnustep-base.so` instead of directly to `libgnustep-base.so.1.27`, we could fix this for future version updates.

**Comment by KenjiTakahashi** [comment]
A SONAME change indicates breaking changes in the ABI.
The only way to properly deal with this is to relink the app against new version. For packages in official repos, maintainers do it for us (case in point: https://github.com/archlinux/svntogit-community/commit/e4ba9ea11c4b758e744f4ca9e2d58c9de8c4b91c).
That it works by symlinking older name to the newer one is based purely on luck.
And on a side note, there is no way to link directly to `libgnustep-base.so`, as linking is done against an actual object file, not a symlink (or file) name.
Just a prose of life 🤷.
