### ISSUE TITLE
install method is not work for me

### ISSUE THREAD

**Issue by Johnkb101313** [KenjiTakahashi/pacmixer#24]
1. At first, I git clone the project
2. then I try to follow the installation to install pacmixer, and the terminal log output an error : 
`install: cannot stat 'pacmixer': No such file or directory`

i have to check the mk.sh, and i saw this:
`install -m 755 pacmixer "${BIN}"`
and i don't have "pacmixer" file in my folder

Is there any way that I can install pacmixer?

**Comment by KenjiTakahashi** [comment]
It would mean that it fails to compile the binary. Any more output before that error line? Most likely you're missing some dependency package.

**Comment by Johnkb101313** [comment]
Oh!, thank you, you remind me.
I don't know why ninja is losing at that time.
By the way, the problem is solved, thank you so much.

and sorry about my English, English is not my native language, hope you can get it
