### ISSUE TITLE
pacmixer depends on old gnustep-base after update

### ISSUE THREAD

**Issue by Mikkihiiri27** [KenjiTakahashi/pacmixer#25]
Hi, would you change pacmixer to depend on the new version of gnustep-base, please? It was updated to 1.30 recently and pacmixer depends on 1.29. I solved the issue for myself by downgrading it with pacman (am on arch) using my existing cache of it and ignoring the package update in pacman.conf for the time being. Thank you, the program is superb!

**Comment by KenjiTakahashi** [comment]
There is no hard dependency on any specific version in the project itself, any 1.x should work fine.
I guess you might mean that the AUR package stopped working?
Just rebuild it with the new GNUStep installed and it should work.
I will check it and bump the release over the weekend, when I'm back at my main rig.

**Comment by Mikkihiiri27** [comment]
Yes, the AUR package. It complained that it depended on the earlier version, not recognizing the new version. Thank you.

**Comment by KenjiTakahashi** [comment]
Alright, I've pushed an update to the AUR package. It works fine after a rebuild AFAICT.

BTW: Here is some reasoning on why this happens sometimes: https://github.com/KenjiTakahashi/pacmixer/issues/22.
Also, in the future, it is best to raise such issues in AUR instead.
