### ISSUE TITLE
Feature request: make filter customizable

### ISSUE THREAD

**Issue by Fuco1** [KenjiTakahashi/pacmixer#8]
Make the default filter customizable: most of the time I want to see the F2 screen (Playback), so that should be the default.

**Comment by KenjiTakahashi** [comment]
Implemented in current master. Will hopefully get released as 0.6 soon. Please refer to the new [configuration](https://github.com/KenjiTakahashi/pacmixer#configuration) section on how to set it.

**Comment by Fuco1** [comment]
Thanks! :)
