### ISSUE TITLE
Feature request: add J/K or PageUp/PageDown to adjust levels faster

### ISSUE THREAD

**Issue by Fuco1** [KenjiTakahashi/pacmixer#9]
These should go 10-15 times faster than just j/k to quickly adjust the levels.

**Comment by KenjiTakahashi** [comment]
Implemented as well :-). Added J/K (or Shift+Up/Shift+Down, respectively) meant for faster adjusts. Speeds are configurable for both j/k and J/K (default to 1 and 10) in the settings file.

**Comment by Fuco1** [comment]
:+1: thanks!
